### ISSUE TITLE
Indexer für domain und cms_system

### ISSUE THREAD

**Issue by reinhardt** [loechel/lmu.policy.base#12]
Die Felder "domain" und "cms_system" im Solr-Schema sollen für alle Content-Objekte mit Werten gefüllt werden, die portalweit gesetzt werden können sollen (LMU Properties?).

**Comment by loechel** [comment]
Im Indexer bitte noch das Feld context_path_string setzten, dies ist der relative Pfad zum Object von Plone Naviagtion Root / Portal Root udn nicht dwie der path_string vom Zope Root aus.

Setzten in LMU Properties ist gut.

**Comment by reinhardt** [comment]
Siehe #18
