### ISSUE TITLE
Edit View Bilder und Dateien hat ein Reload Problem

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#16]
Update view funktioniert nur ein mal, 

Update nach Sort View klappt auch nicht

JavaScript in umgebenden Context verschieben.

**Comment by reinhardt** [comment]
> Update view funktioniert nur ein mal,

Meinst Du das Aktualisieren der Bilder und Dateien, nachdem man etwas hoch geladen hat? Funktioniert bei mir problemlos.

> Update nach Sort View klappt auch nicht

Geht bei mir auch.

> JavaScript in umgebenden Context verschieben.

Was genau meinst Du mit "umgebenden Context"? Was willst Du erreichen?

**Comment by loechel** [comment]
Fehler gefunden und behoben,

Trat nur im IE auf und war eine Folge von Caching im Browser die bei JSON Anfragen bei zweiten mal immer das gleicher ergebnis mitgegeben hat.
