### ISSUE TITLE
updated_search geht auf etwas anderes als die Search

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#19]
Wir haben in der Search eine Customisierung drin, die eine Liste von Fiona-Objekttypen bei der Suche berücksichtigt. Die updated_search View aus plone.app.search greift aber in der Suche und lädt nur Plone Inhalte nach.

Bitte diese View überschreiben und gleiche Anpassung wie für die Search verwenden

**Comment by reinhardt** [comment]
Ich meine, das ging schon mal. Wenn ich richtig liege ist das nicht viel Aufwand. Würde ich mir wahrscheinlich zuerst ansehen.

**Comment by reinhardt** [comment]
Ging wahrscheinlich schon mal in einer älteren Version von plone.app.search. Fix ist im Branch search-fixes.

**Comment by loechel** [comment]
danke, wie besprochen mittelfristig die Search facets ncoh mit updaten.

Zwischenzeitlich wäre als übergangslösung ein verzicht auf updated_search auch sinnvoll, solange dadurch die Suche neue geladen wird.

**Comment by reinhardt** [comment]
> wie besprochen mittelfristig die Search facets ncoh mit updaten

Ist jetzt auch im selben Branch!

**Comment by loechel** [comment]
merged
