### ISSUE TITLE
Escaping in Search-Results

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#20]
Plone macht ein Escaping der Suchergebnisse,

Resultat ist, das Buchstaben in den Suchformularen auftauchen die nicht angezeigt werden sollten, z.B. &shy; oder # als %23 in URLs maskiert werden und somit der Link nicht mehr funktioniert.
Bitte ansehen und die Masierung aufheben.

Beispiele: 
https://www.intranet.verwaltung.uni-muenchen.de/search?SearchableText=Tarif&facet.field=portal_type

**Comment by reinhardt** [comment]
Ich tu mir hier schwer mit dem Testen - ich bräuchte ein paar Fiona-Daten, bei denen das Problem auftritt, in meinem Solr. Trotzdem habe ich mal einen Fix probiert; kannst Du mal testen, ob der was bringt? Siehe branch search-fixes

**Comment by loechel** [comment]
Funktioniert, ich werde dir einen Solr Dump besprgen udn schicken.
