### ISSUE TITLE
SearchFacets limitieren

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#21]
Es ist gewünscht, in den Search Facets nur eine Teilmenge der Facetten anzuzeigen

Hierzu wäre es sinnvoll ähnlcih wie bei den extra_types_searched ein zusätzliches Feld in den Site Properties zu haben, wo die Objekt-Klassen über die eine facetierung erfolgen soll abgebildet sind:

bsp. Soll über alles Gesucht werden, aber nur folgende 7 Typen in der Facetierung auftauchen:

Blog-Beitrag
Pinnwand-Eintrag
Person (zuv_person)
Service (zuv_service)
...
Dateien

Die Objekte sollen nach Möglichkeit aus Bezeichner in der Solr und einer Übersetzung bestehen 
zuv_person --> Person

**Comment by reinhardt** [comment]
Ich glaube das Ausschließen von Typen ist konzeptionell schon vorgesehen, muss wahrscheinlich noch konfiguriert werden.

**Comment by reinhardt** [comment]
Sollen die Typen wirklich nur in der Facettierung ausgeschlossen werden oder sollen sie gar nicht in den Suchergebnissen auftauchen? Sie nur aus der Facettierung auszuschließen könnte zu unerwarteten Effekten führen.

**Comment by loechel** [comment]
Ja wir wollen wirklich eine Submenge in der Facetierung haben.

Bei einer normalen Suche soll über alle Elemente gesucht werden, mit der Aktiven Facteierung nur über die ausgewählten.

Ich gehe von zwei möglichen Nebeneffekten aus,
- Die Anzahl der Ergebnisse ist größer als die Summer der Facetten Elemente
- Das löschen der Facetten für nicht auf die ursprüngliche Suche zurück, es ist immer noch ein Filter aktiv

erstes ist grundsätzlich zu erwarten und zu akzeptieren, ggf. ein nicht klickbares sonstiges in den Facetten anlegen,

zweites sollte abgefangen werden und nicht auftretten.

**Comment by reinhardt** [comment]
Siehe Branch limit-facets. Der Code geht davon aus, dass nur nach einem Feld facettiert wird, dem portal_type. Wenn noch Facetten dazu kommen dann klappt das so nicht mehr!

Ich habe in den Portal Properties das Feld types_search_facets gefunden und benutzt. Sag bescheid wenn das nicht so gedacht war.

Typnamen müssten bereits übersetzt werden. Mit den Plone-Typen klappt es. Wenn es mit den Fiona-Typen Probleme gibt dann werde ich mal schauen, dass ich den Solr-Dump bei mir einbinde um das zu testen.

**Comment by reinhardt** [comment]
Gerade noch einen Fix für die Übersetzungen eingebaut. Müsste jetzt komplett sein.

**Comment by loechel** [comment]
Danke passt
