### ISSUE TITLE
Anpassen der Status Message mit sinnvolleren Texten

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#26]
Die Status Message beim Speichern, aNlegen oder Workflow Änderen von Inhalten in Plone ist immer Identisch. Teilweise wäre es sinnvoll hier spezifischere Meldungen auszugeben.

Statt: Workflowstatus geändert --> Blog-Beitrag veröffentlicht

**Comment by reinhardt** [comment]
Dazu muss man wohl an mehreren Stellen angreifen. Habe gerade heraus gesucht, wo die jeweiligen Status Messages ausgegeben werden:
- Anlegen: plone.dexterity.browser.add.DefaultAddForm.handleAdd()
- Speichern: plone.dexterity.browser.edit.DefaultEditForm.handleApply()
- Workflow: Products.CMFPlone:skins/plone_form_scripts/content_status_modify.py

content_status_modify.py kann man auf jeden Fall anpassen. DefaultAddForm und DefaultEditForm sind etwas schwieriger zu ersetzen, außer man patcht sie einfach, was aber die Wartung hässlich macht. DefaultEditView und DefaultAddView (die Views, die die Forms einbinden) wiederum kann man per zcml für das eigene Browser Layer überschreiben. Das ist vielleicht der beste Ansatz.

Ich kann mich morgen mal an einer Implementation versuchen.

**Comment by loechel** [comment]
Workflow wäre am wichtigsten, ist leider komplizierte als man denkt, da es kein skin py sondern ein skin cpy mit cpy.metadata und vpy ist (https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/skins/plone_form_scripts). 

Bei meinem ersten versuch via Template Overwrite wollte das nicht, danach war kein Workflow Change mehr möglich.

Wäre zu überlegen, ob ggf. das sauber in eine Browserview überführt wird und dann für unser Projekt einen Backport erfolgt.

**Comment by reinhardt** [comment]
Aktueller Stand ist in custom-status-messages. Die Übersetzungen greifen noch nicht aber die Workflow Status Message sagt jetzt den Typ und die Transition.

**Comment by reinhardt** [comment]
Status Messages scheinen nur als Ganzes übersetzt zu werden. Wenn ich zwei Status Messages hinzu füge, eine für den Typnamen und eine für die Transition, dann werden sie übersetzt. Eine andere Alternative wäre vielleicht, für jeden Typnamen alle Phrasen separat als Übersetzung zu hinterlegen, also "Blog-Beitrag wurde veröffentlicht", "Blog-Beitrag wurde zurückgezogen", usw. jeweils als eine Übersetzung.

**Comment by reinhardt** [comment]
Hatte gerade noch eine andere Idee. Wenn man zope.i18n.translate importiert und die Einzelteile explizit übersetzt dann geht es auch. Siehe custom-status-messages
