### ISSUE TITLE
setuphandler AutoUserMakerPASPlugin

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#5]
bitte via Setuphandler eine Instanz von Products.AutoUserMakerPASPlugin hinzufügen udn mit folgenden Werten belegen:

User ID: HTTP_EDUPersonPrincipalName
Full_name: HTTP_DISPLAYNAME
email: HTTP_MAIL

AutoUpdate: true

**Comment by reinhardt** [comment]
Schau ich mir auch noch an.

**Comment by reinhardt** [comment]
Ist mit in Pull Request #8.

**Comment by loechel** [comment]
passt und gemerged
