### ISSUE TITLE
setupHandler für Gruppenzugehörigkeit

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.policy.base#6]
https://pypi.python.org/pypi/Products.ShibbolethPermissions
bzw. Products.AutoRoleFromHostHeader

in ACL-users erstellen
so dass cms-admins-insp im HTTP-Header Groupmembership auf Site-Admin-Rolle mappt.

**Comment by reinhardt** [comment]
Es scheint hier kein "in progress"-Label zu geben und ich kann auch keins hinzu fügen. Auf jeden Fall schau ich mir das Ticket jetzt an.

**Comment by reinhardt** [comment]
Siehe #8

**Comment by loechel** [comment]
merged
